version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_blog
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        working_dir: /var/www
        networks:
            - laravel_blog_network
        depends_on:
            - database

    nginx:
        image: nginx:alpine
        container_name: laravel_blog_nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_blog_network

    database:
        image: postgres:16
        container_name: laravel_blog_postgres
        restart: always
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
        volumes:
            - postgres_db_vol:/var/lib/postgresql/data
            - ./postgres-init:/docker-entrypoint-initdb.d
        networks:
            - laravel_blog_network
        ports:
            - "5432:5432"

    phpmyadmin:
        image: adminer:4.8.1
        container_name: laravel_blog_adminer
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - laravel_blog_network

networks:
    laravel_blog_network:
        driver: bridge
volumes:
    postgres_db_vol:
        driver: local
